### ISSUE TITLE
번역이 좀 이상한 부분..

### ISSUE THREAD

**Issue by tmheo** [jehyunlee/texts#1]
안녕하세요, 제현님

공유해주신 번역글들 너무 감사하게 잘 보고 있습니다.

읽어보다 번역이 어색한 부분이 있어서 이슈로 등록합니다.

https://github.com/jehyunlee/texts/blob/master/estimating_an_optimal_learning_rate_for_a_deep_neural_network/text.md 에서

> 다른 값 여러 개를 넣고 언제 학습 속도를 유지한 채 손실이 가장 적은지를 비교할 수 있다.

라는 문장이 있는데, 좀 어색하게 느껴지는데요.

_다른 값 여러 개를 넣고 학습 속도를 유지한 채 언제 손실이 가장 적은지를 비교할 수 있다._

라고 하는게 좀 더 맞는 표현이 아닐지 합니다..

**Comment by jehyunlee** [comment]
허태명님 말씀이 맞습니다. 제가 어이없이 했네요; 수정하겠습니다.
좋은 의견 감사드립니다! ^^

**Comment by jehyunlee** [comment]
지금 밖이라 수정이 좀 어렵습니다. 이따 밤에 수정 반영하겠습니다!

**Comment by jehyunlee** [comment]
수정내용 반영했습니다. 피드백 진심으로 감사드립니다 ^^

**Comment by tmheo** [comment]
감사합니다~
