### ISSUE TITLE
Linux_on_Dex 이미지 다운로드 관련

### ISSUE THREAD

**Issue by BraINstinct0** [jehyunlee/texts#2]
[해당 부분](https://github.com/jehyunlee/texts/blob/master/Linux_on_Dex/text.md#3-linux-image-file-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-%EB%B0%8F-%EC%95%95%EC%B6%95%ED%95%B4%EC%A0%9C)
여기서 windows에서는 다운로드가 안된다고 하는데, 저는 Windows 10 기준 Chrome에서 직접 다운로드 링크로 들어갈 시 정상적으로 다운로드가 완료됩니다. 추가적으로, windows에서도 wget을 하는 경우 wsl 없이도 가능한 [방법](https://zetawiki.com/wiki/%EC%9C%88%EB%8F%84%EC%9A%B0_wget)이 있네요.
참고 바랍니다

**Comment by jehyunlee** [comment]
의견 감사합니다! 
저는 windows10 chrome에서 다운로드를 할 때 자꾸 오류가 나더라구요. 구글링을 해보니 저와 같은 증상이 많아서 그렇게 적었습니다. 말씀하신 부분을 글에 반영해서 수정해 두겠습니다.

**Comment by jehyunlee** [comment]
수정 반영했습니다. 진심으로 감사드립니다 ;)
